version: "1.0"
info:
  model: int-scaffold
packages:
- name: MyExtGitProject
  gitServerName: Git
  gitUrl: https://github.com/sagmaak
  gitUsername: sagmaak
  gitBranch: main
- name: GitDemo
  version: "1.0"
  gitServerName: Git
  gitUrl: https://github.com/sagmaak
  gitUsername: sagmaak
  gitBranch: main
services:
- serviceName: project.myextgit.documenttypes:SimpleOrder
  packages:
  - name: MyExtGitProject
    version: "1.0"
  - name: GitDemo
    version: "1.0"
- serviceName: project.myextgit.integrations:EdgeFS1
  packages:
  - name: MyExtGitProject
    version: "1.0"
  - name: GitDemo
    version: "1.0"
- serviceName: pub.date:currentNanoTime
  packages:
  - name: WmPublic
    version: 11.1.0.0.2043
- serviceName: project.myextgit.integrations:addNums
  packages:
  - name: MyExtGitProject
    version: "1.0"
  - name: GitDemo
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2043
- serviceName: project.myextgit.integrations:shipOrder
  packages:
  - name: MyExtGitProject
    version: "1.0"
  - name: GitDemo
    version: "1.0"
